- name: Github
  endpoint: https://www.github.com
  frequency: 5s
  expectedCode: 200

- name: Google
  endpoint: https://www.google.com
  frequency: 1m
  expectedCode: 200

- name: My Unstable Service
  endpoint: http://localhost:8080/unstable
  frequency: 25s
  expectedCode: 200

- name: Always Down Service
  endpoint: http://localhost:8080/asdfasdfj
  frequency: 20s
  expectedCode: 200

- name: Inxidents
  endpoint: https://incidents.fly.dev/
  frequency: 1h45m
  expectedCode: 200
